export * from './customer-legal.model';
export * from './customer-legal.search.model';
export * from './customer-legal-popup.service';
export * from './customer-legal.service';
export * from './customer-legal-update.component';
export * from './customer-legal-delete-dialog.component';
export * from './customer-legal-detail.component';
export * from './customer-legal.component';
export * from './customer-legal.route';
