version: '2'
services:
    nextlogix-app:
        image: nextlogix
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nextlogix-postgresql:5432/nextlogix
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=nextlogix-elasticsearch:9300
        ports:
            - 8080:8080
    nextlogix-postgresql:
        extends:
            file: postgresql.yml
            service: nextlogix-postgresql
    nextlogix-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: nextlogix-elasticsearch
