export * from './detail-form.model';
export * from './detail-form.search.model';
export * from './detail-form-popup.service';
export * from './detail-form.service';
export * from './detail-form-update.component';
export * from './detail-form-delete-dialog.component';
export * from './detail-form-detail.component';
export * from './detail-form.component';
export * from './detail-form.route';
